### ISSUE TITLE
Hak hak user

### ISSUE THREAD

**Issue by malanadya** [malanadya/rk#2]
Halo apakah teman2 selaku client bisa me list apa saja hak2 user? cc @jeffrynasri

**Comment by mhanifamrizal** [comment]
untuk warga tetap : Akses mengajukan surat, mengirimkan saran dan keluhan, melihat dan mengubah data warga,melihat agenda kegiatan,,pengumuman dan laporan, rekapitulasi keuangan 

warga sementara : Akses mengajukan surat, mengirimkan saran dan keluhan, melihat data warga, melihat agenda kegiatan, pengumuman dan laporan rekapitulasi keuangan

Ketua rt : Akses penuh ke semua data
